---
name: Build Windows Binary

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history is available

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up virtual environment
        run: |
          python -m venv venv
          venv\Scripts\activate

      - name: Install dependencies
        run: |
          venv\Scripts\pip install -r requirements.txt -c constraints.txt

      - name: Build with PyInstaller
        run: |
          venv\Scripts\pyinstaller comic_upscale.spec --distpath dist/comic_upscaler

      - name: Create zip archive
        run: |
          $version = (git describe --tags --abbrev=0)
          Compress-Archive -Path dist/comic_upscaler/* -DestinationPath comic_upscaler_windows_$version.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: comic_upscaler-windows-${{ github.ref_name }}
          path: comic_upscaler_windows_${{ github.ref_name }}.zip